runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(html|css|js|jpg|png))
  static_files: build/\1
  upload: build/(.*\.(html|css|js|jpg|png))

- url: /.*
  static_files: build/index.html
  upload: build/index.html
